### ISSUE TITLE
Use of HTTPS for requests

### ISSUE THREAD

**Issue by bacloud14** [SJellen/weather#15]
Some browsers implement blocking mixed content policy.
Just pointing the [implemented version](https://weather-ashen.vercel.app/), I mean 'environment' variables (not code).

Host would be `https://api.openweathermap.org/` instead of `http://api.openweathermap.org/`

**Comment by SJellen** [comment]
Thanks.
Just fixed it. 
Not sure why I didnt get a notification in Oct.
 But oh well. Thanks for the find.

**Comment by bacloud14** [comment]
![image](https://user-images.githubusercontent.com/10267332/146826772-69f6aa07-e628-4c2b-baad-feec8d241943.png)

Still HTTP on my side 😄

**Comment by SJellen** [comment]
What is the url that your using?
The url in at the top of the repo was dead and they gave it to someone else. 
I don't have a SearchBar component and I dont use .jsx 
I did have that http issue though. Should be fixed now. This is the current https://cocky-spence-832819.netlify.app/

**Comment by bacloud14** [comment]
very nice, yes I was basing on that URL.
